RUBY-2458 2458
mongodb/mongo-ruby-driver pull request #2147
Opened 2020-11-27 21:44 UTC by p-mongo

https://jira.mongodb.com/browse/RUBY-2458

2020-11-27 22:10 UTC, p-mongo commented
https://jira.mongodb.org/browse/RUBY-2458

2020-12-02 15:20 UTC, durran requested changes
Just a few nits - doesn't look like the Evergreen failures are directly related to this PR so LGTM after those 2 comments.

2020-12-02 15:20 UTC, durran commented on lib/mongo/monitoring.rb
> +            server.address, Time.now-start_time, exc,
Bit of a nit but I would expect all parameters do be on new lines or not - not a combination of them.

2020-12-02 15:20 UTC, durran commented on lib/mongo/monitoring.rb
> +            server.address, Time.now-start_time,
Same as above with parameters.

2020-12-02 16:08 UTC, p-mongo commented
All of the positional parameters were on the same line but I made each of them take up their own line as you requested.

2020-12-02 18:22 UTC, durran approved these changes
LGTM

2020-12-03 01:48 UTC, merged