RUBY-3097 Use monotonic time for deadlines
mongodb/mongo-ruby-driver pull request #2646
Opened 2022-10-03 19:07 UTC by Neilshweky

2022-10-04 16:47 UTC, Neilshweky commented on spec/mongo/session_transaction_spec.rb
> +        start = Mongo::Mongo::Utils.monotonic_time
```suggestion
        start = Mongo::Utils.monotonic_time
```

2022-10-04 16:47 UTC, Neilshweky commented on spec/mongo/session_transaction_spec.rb
> +          start = Mongo::Mongo::Utils.monotonic_time
```suggestion
          start = Mongo::Utils.monotonic_time
```

2022-10-07 08:15 UTC, comandeo requested changes

2022-10-07 08:15 UTC, comandeo commented on spec/support/utils.rb
> +    deadline = Utils.monotonic_time + 15
```suggestion
    deadline = Process.clock_gettime(Process::CLOCK_MONOTONIC) + 15
```

2022-10-07 08:15 UTC, comandeo commented on spec/support/utils.rb
> +      if Utils.monotonic_time >= deadline
```suggestion
      if Process.clock_gettime(Process::CLOCK_MONOTONIC) >= deadline
```

2022-10-07 08:15 UTC, comandeo commented on spec/support/utils.rb
> +    deadline = Utils.monotonic_time + 15
```suggestion
    deadline = Process.clock_gettime(Process::CLOCK_MONOTONIC) + 15
```

2022-10-07 08:15 UTC, comandeo commented on spec/support/utils.rb
> +      if Utils.monotonic_time >= deadline
```suggestion
      if Process.clock_gettime(Process::CLOCK_MONOTONIC) >= deadline
```

2022-10-20 16:12 UTC, merged