Add write timeout
mongodb/mongo-ruby-driver pull request #2843
Opened 2024-02-26 12:07 UTC by comandeo-mongo

2024-03-04 18:13 UTC, jamis requested changes

2024-03-04 18:13 UTC, jamis commented on lib/mongo/socket.rb
> +        data
If `data` is initialized to the empty string, could we get rid of the duplication here by letting the loop do all the heavy lifting?

```suggestion
        "".tap do |data|
          while data.length < length
            socket_timeout = deadline - Utils.monotonic_time
            if socket_timeout <= 0
              raise Mongo::Error::TimeoutError
            end
            chunk = read_from_socket(length - data.length, socket_timeout: socket_timeout, csot: true)
            unless chunk.length > 0
              raise IOError, "Expected to read > 0 bytes but read 0 bytes"
            end
            data << chunk
          end
        end
```

2024-03-04 18:13 UTC, jamis commented on lib/mongo/socket.rb
> +        data
I know this was just copied from the original implementation of `#read`, but we can probably get rid of the duplication as was suggested above for `read_with_timeout`, by letting the loop do all the work:

```suggestion
        "".tap do |data|
          while data.length < length
            chunk = read_from_socket(length - data.length, socket_timeout: socket_timeout)
            unless chunk.length > 0
              raise IOError, "Expected to read > 0 bytes but read 0 bytes"
            end
            data << chunk
          end
        end
```

2024-03-05 12:16 UTC, comandeo-mongo commented on lib/mongo/protocol/message.rb
> +          end
I think it can be simplified even more: `read_options = options.slice(:timeout, :socket_timeout)`

2024-03-05 15:25 UTC, jamis approved these changes
❤️ Very nice! Just one bit with some lines that I don't think are necessary any more, but other than that I think it's good to merge. 👍

2024-03-05 15:25 UTC, jamis commented on lib/mongo/protocol/message.rb
> +          end
Good call! I missed that `read_options` is a new Hash. 👍

2024-03-05 15:25 UTC, jamis commented on lib/mongo/protocol/message.rb
> +        %i[timeout socket_timeout].each do |key|
I don't think these lines are still necessary...

2024-03-06 08:54 UTC, merged